name: Run TGI Benchmark
run-name: ${{ inputs.model }}-${{ inputs.precision }}-${{ inputs.framework }}-${{ inputs.experiment-name }}
on:
  workflow_dispatch:
    inputs:
      runner:
        description: "Runner to run on"
        required: true
        default: "mi325x-amd_0"
      docker-image:
        description: "Docker image to run"
        required: true
        default: "ghcr.io/huggingface/text-generation-inference:latest-rocm"
      model:
        description: "Model to run"
        required: true
        default: "mistralai/Mistral-7B-Instruct-v0.2"
      precision:
        description: "Precision to run"
        required: true
        default: "float16"
      framework:
        description: "Framework to run"
        required: true
        default: "tgi"
      experiment-name:
        description: "Experiment name"
        required: true
        default: "tgi-mistral-7b-test"

jobs:
  benchmark:
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: actions/checkout@v4
      - name: Run benchmark
        run: |
          docker run \
            -e HF_TOKEN=${{ secrets.HF_TOKEN }} \
            -v /mnt/hf_hub_cache:/root/.cache/huggingface/hub \
            ${{ inputs.docker-image }} \
            --model-id ${{ inputs.model }} \
            --dtype ${{ inputs.precision }} \
            #--framework ${{ inputs.framework }} \
            --experiment_name ${{ inputs.experiment-name }}
